name: Build Host and Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore WindowsHost/PicoSidekick.Host.sln

    - name: Build project
      run: dotnet build WindowsHost/PicoSidekick.Host/PicoSidekick.Host.csproj --configuration Release --no-restore

    - name: Publish build output
      run: dotnet publish WindowsHost/PicoSidekick.Host/PicoSidekick.Host.csproj --configuration Release --output ./publish /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /p:PublishSingleFile=true
    
    - name: Archive build output
      uses: actions/upload-artifact@v4
      with:
        name: PicoSidekickHost
        path: ./publish

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: PicoSidekickHost
        
    - name: Zip build output
      run: zip PicoSidekickHost.zip . -r
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Release ${{ github.ref_name }}"
        files: PicoSidekickHost.zip
        draft: false
        prerelease: false
